# Setup
title: 'Minicurso de Linux e Git'
url: https://missing.csail.mit.edu

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true